### PR TITLE
Test mode for quickly checking S3 connection settings.

### PR DESCRIPTION
**Pull request by bradobro**
Thanks again for such a useful package! I really learned a lot about Ruby from your lean code.

This PR proposes a test mode for quickly testing the S3 setup. It would need docs.

### CODE REVIEW

**Comment by Manfred** [comment]
Can you describe the scenario in which you would use the test (in which you push a file to S3) instead of just trying to push the bundle to S3?

**Comment by bradobro** [comment]
Thanks for asking! I'm not too attached to what sort of data I use to test the upload, just that the test can run quickly even when my bundle is big and slow to build. Here's a rough scenario:

AS A Rails app deployer 
WHO has a bundle that takes 10 minutes to build (Nokogiri + a few other native gems)
AND WHO is inexperienced at configuring S3 permissions
OR WHO can't easily tweak S3 settings (because, say, you work for big organization and it's not good for your job to ask the AWS admin to re-check his permissions until you're really sure they are  the problem.)

SO THAT I can efficiently make sure that my WAD S3 configuration is correct

I WANT a quick test that isolates S3 configuration
AND avoids the recurrent delay of waiting my bundle to build and tar.

**Comment by Manfred** [comment]
Ok, in that case it makes more sense to write documentation on how to check the S3 configuration from your workstation.

By the way, Travis-CI now has bundle caching built-in for private repositories.

http://about.travis-ci.org/docs/user/caching/#Caching-directories-(Bundler%2C-dependencies)

**Comment by bradobro** [comment]
Ok, thanks for considering this, Manfred. (We're using WAD because it's a public project.)

**Pull request closed without merging**
