### PR TITLE
Use curl instead of net/http

### PR DESCRIPTION
**Pull request by eric**
To speed up download and upload, use `curl` instead of `Net::HTTP`.

Also adds flexibility for dealing with other kinds of commands than bundler.

### CODE REVIEW

**Comment by madrobby** [comment]
Isn't a design goal of WAD to not have dependencies? If this makes things faster though it could use curl if it's installed (and works) and fall back to Ruby if not.

**Comment by Manfred** [comment]
Can you post some benchmarks about how much faster it is?

**Comment by eric** [comment]
If the code is supposed to be running on Travis CI and the README is suggesting using curl to download the script at build time, is it unreasonable to expect curl to be available any more than expecting tar or bzip2 to be installed?

**Comment by madrobby** [comment]
@eric It's one less thing that can break (certificates, etc).

**Comment by eric** [comment]
Honestly, switching from `Net::HTTP` to `curl` fixed interacting with S3 buckets with dots in them. `Net::HTTP` doesn't validate wildcard certificates when accessing multi-level subdomains, so [this](https://github.com/Fingertips/WAD/blob/254605ccb2ccf8cd7e2aff0f8ae785429574e21c/src/01_presss.rb#L71-L74) doesn't work if your bucket has a dot in it. You need to use the `https://#{domain}/#{bucket_name}/#{path}` notation to access a bucket with dots in it from `Net::HTTP`.

Has there been a problem with the certificates on the Travis CI VMs not being okay or is this just a hypothetical concern?

**Comment by madrobby** [comment]
@eric No idea about Travis, but I had problems with certificates before. I'm now always including my own set of certificates in projects so that OS updates etc. can't break stuff.

**Comment by Manfred** [comment]
Eric, I appreciate all the work you're putting in! Can you help me decide whether it makes sense to depend on cURL? I'm not entirely convinced this is a better solution. All your other improvements could be made without depending on cURL.

One of the problem I have with it is that most of the functionality is actually changed in Presss, which is a separate library we use for S3. I would like to keep this identical to the upstream version. Presss runs on platforms without cURL. It also runs in environments where you don't want to shell out. Spawning shells is rather resource intensive and might cause permission problems when running, for example, in a web backend process.

How much faster is uploading and downloading with cURL? Can you post some benchmarks?

**Comment by eric** [comment]
I can try to create some benchmarks, but they're entirely related to the size of the file being uploaded/downloaded and the connectivity of the person running it.

The reason for the API change for Presss is that it requires that the entire file be loaded into the ruby process (which could be 100MB or more), which puts a lot of pressure on the GC.

My first work was using `Net::HTTP` with the new API that did streaming uploads/downloads, but I decided that if the goal of WAD was to make Travis CI builds as fast as possible, it seemed reasonable to just use curl directly instead of ruby to do the heavy lifting.

**Comment by Manfred** [comment]
We already have a version of Presss lying around that does streaming uploads and downloads. I haven't had time to merge it in unfortunately.

I like the URL changes you were working on to support dots in buckets. I think we can simplify that a bit by not allowing the domain notation (there doesn't seem to be a point).

I expect to have some time today or tomorrow to merge some one these changes.

**Comment by Manfred** [comment]
Eric, I love your work! This pull request is becoming a bit too large so I'm not going to pull it all in. I hope you don't mind if I pick a choose a few of your ideas?

**Comment by eric** [comment]
That's fine with me.

travis-ci is in the process of rolling this out internally in the pull request I referenced, so the usefulness of this may be reduced as time goes on...

**Comment by Manfred** [comment]
Yes, I know, that's why I don't want to spend too much time on it (:

**Comment by eric** [comment]
Feel free to pull whatever you think is relevant.

My branch is working great for the things I need it for.

**Pull request closed without merging**
